name: buildx

on:
  pull_request:
    branches: master
  push:
    branches:
      - master
      - etcdn-release-*
    tags:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Run Buildx
        run: |
          docker buildx build \
          --platform linux/amd64 --build-arg ARCH=amd64 --build-arg RPM_ARCH=x86_64 \
          -t etcdnexx/netshoot:latest -o type=docker -f ./Dockerfile .
      - name: Push
        if: ${{ github.ref == 'refs/heads/master' || contains(github.ref, 'release') }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          TAG=$(cat VERSION)
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push etcdnexx/netshoot:latest
